import Pagination from '../components/Pagination';
import useTablePagination from '../hooks/useTablePagination';
import { creationDate } from '../date';
import StatusBadge from '../components/StatusBadge';
import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import DashboardLayout from '../components/DashboardLayout';
import PageHeader from '../components/PageHeader';
import Loader from '../components/Loader';
import PopupMessage from '../components/PopupMessage';
import { apiRequest } from '../api';
const money=value=>`₹${Number(value||0).toLocaleString('en-IN')}`;
function Address({title,address}){
  return <section className="product-panel"><h2 className="product-panel-title">{title}</h2>{address?<p className="text-sm leading-7 text-slate-500">{address.name}<br/>{address.address}{address.landmark&&<><br/>{address.landmark}</>}<br/>{address.city}, {address.state} – {address.pincode}<br/>{address.phone}<br/>{address.email}</p>:<p className="text-sm text-slate-400">No address recorded.</p>}</section>;
}
export default function OrderDetails(){
  const {id}=useParams();const [result,setResult]=useState({loading:true});const [attempt,setAttempt]=useState(0);
  useEffect(()=>{const controller=new AbortController();async function load(){setResult({loading:true});try{const data=await apiRequest(`/admin/orders/${id}`,{signal:controller.signal});if(!controller.signal.aborted)setResult({loading:false,order:data.order});}catch(error){if(!controller.signal.aborted)setResult({loading:false,error:error.message});}}load();return()=>controller.abort();},[id,attempt]);
  const order=result.order;
  const paging=useTablePagination(order?.items||[],10,id);
  return <DashboardLayout><main className="admin-page"><PageHeader title="Order Details" description={order?`Order #${order.orderId??'—'}`:'View customer order'}><Link to="/orders" className="admin-button-secondary">Back to orders</Link><Link to={`/orders/${id}/edit`} className="admin-button-primary">Edit order</Link></PageHeader>{result.loading?<Loader label="Loading order"/>:result.error?<div><PopupMessage message={result.error}/><button className="admin-button-secondary" onClick={()=>setAttempt(n=>n+1)}>Try again</button></div>:<><section className="product-panel mb-5"><dl className="grid gap-5 text-sm sm:grid-cols-2 lg:grid-cols-4">{Object.entries({Customer:order.user?.name||'Deleted account',Email:order.user?.email||'—',Status:order.status,Payment:order.paymentMethod==='cod'?'Cash on Delivery':order.paymentMethod||'—','Order date':new Date(order.createdAt).toLocaleString('en-IN'),'Order ID':`#${order.orderId??'—'}`}).map(([label,value])=><div key={label}><dt className="mb-2 text-slate-400">{label}</dt><dd className="break-words font-medium">{label==='Status'?<StatusBadge status={value}/>:value}</dd></div>)}</dl></section><section className="product-panel mb-5"><h2 className="product-panel-title">Ordered Items</h2><div className="admin-table-scroll"><table className="admin-table w-full text-sm"><thead><tr>{['Sr. No.','Product','Color / Size / Type','Quantity','Unit price','Total','Created On'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{paging.rows.map((item,index)=><tr key={item._id||index}><td className="font-medium text-slate-700">{paging.offset+index+1}</td><td>{item.product?<Link className="text-blue-600" to={`/product/${item.product}`}>{item.name}</Link>:item.name}</td><td>{[item.options?.color,item.options?.size,item.options?.type].filter(Boolean).join(' / ')||'—'}</td><td>{item.quantity}</td><td>{money(item.unitPrice)}</td><td>{money(item.unitPrice*item.quantity)}</td><td className="whitespace-nowrap">{creationDate(order.createdAt)}</td></tr>)}</tbody></table></div><Pagination page={paging.page} pageSize={paging.pageSize} total={paging.total} onPageChange={paging.setPage} label="order items"/><dl className="ml-auto mt-5 grid max-w-sm gap-3 text-sm"><div className="flex justify-between"><dt>Items subtotal</dt><dd>{money(order.subtotal??order.items.reduce((sum,item)=>sum+item.unitPrice*item.quantity,0))}</dd></div>{order.discount>0&&<div className="flex justify-between text-emerald-600"><dt>Coupon {order.couponCode}</dt><dd>−{money(order.discount)}</dd></div>}<div className="flex justify-between border-t border-slate-200 pt-3 font-semibold"><dt>Total payable</dt><dd>{money(order.totalAmount)}</dd></div></dl></section><div className="grid gap-5 md:grid-cols-2"><Address title="Delivery address" address={order.shipping}/><Address title="Billing address" address={order.billing||order.shipping}/></div></>}</main></DashboardLayout>;
}
