import StatusBadge from '../components/StatusBadge';
import Loader from '../components/Loader';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Pencil, Trash2, Star, ListChecks } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import ProductDialog from '../components/ProductDialog';
import NotificationPopup from '../components/NotificationPopup';
import PopupMessage from '../components/PopupMessage';
import useProduct from '../hooks/useProduct';
import { productImageUrl } from '../api';
const money=(value)=>`₹${Number(value).toLocaleString('en-IN')}`;
export default function ProductDetails(){
  const {id}=useParams();const {loading,product,error,retry}=useProduct(id);
  const [selected,setSelected]=useState(0);const [tab,setTab]=useState('Description');
  const [deleting,setDeleting]=useState(false);const [notification,setNotification]=useState(null);const navigate=useNavigate();
  const images=product?.images||[];
  const specs=product?{Brand:product.brand,Category:product.productType,SKU:product.sku,Stock:product.stock,Status:product.status,Subtitle:product.subtitle,'Lens types':(product.lensTypes||[]).join(', '),'Available colors':(product.availableColors||[]).join(', '),'Available sizes':(product.availableSizes||[]).join(', '),'Offer title':product.offerTitle,Offer:product.offerText,Delivery:product.deliveryInformation,Assurances:(product.assurances||[]).join('; '),Material:product.material,Hinge:product.hinge,Temple:product.temple,Nosepad:product.nosepad}:{};
  return <DashboardLayout><main className="admin-page">{loading?<Loader label="Loading product"/>:error?<div><PopupMessage message={error}/><button onClick={retry} className="admin-button-secondary">Try again</button><Link to="/product" className="admin-button-secondary">Back to products</Link></div>:<>
    <div className="product-details-grid">
      <section className="product-details-gallery"><div className="product-thumb-strip">{images.map((image,index)=><button key={`${image}-${index}`} aria-label={`Show image ${index+1}`} aria-pressed={selected===index} onClick={()=>setSelected(index)}><img src={productImageUrl(image)} alt=""/></button>)}</div><img src={productImageUrl(images[selected]||product.image)} alt={product.name} className="product-large-image"/></section>
      <section className="space-y-5"><h1 className="text-xl font-bold text-slate-800">{product.name}</h1>{product.rating>0&&<p className="flex items-center gap-2 text-sm font-semibold">{product.rating}<Star size={16} className="text-amber-400" fill="currentColor"/></p>}<div className="flex flex-wrap items-center gap-3"><strong className="text-2xl">{money(product.price)}</strong>{product.originalPrice>product.price&&<><del className="text-sm text-slate-400">{money(product.originalPrice)}</del><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-600">{Math.round((1-product.price/product.originalPrice)*100)}% OFF</span></>}</div><p className={`flex items-center gap-2 text-sm font-semibold ${product.stock>0?'text-emerald-500':'text-red-500'}`}><span className="h-2 w-2 rounded-full bg-current"/>{product.stock>0?'In Stock':'Out of Stock'}</p><div><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><ListChecks size={16}/>Key Features</h2>{product.features?.length?<ul className="list-disc space-y-2 pl-5 text-sm text-slate-500">{product.features.map((feature,index)=><li key={index}>{feature}</li>)}</ul>:<p className="text-sm text-slate-400">No features added yet.</p>}</div></section>
      <aside className="product-panel"><dl className="space-y-5">{Object.entries(specs).map(([key,value])=><div key={key} className="grid grid-cols-2 gap-4 text-sm"><dt className="text-slate-400">{key}</dt><dd className="font-medium text-slate-600">{key==='Status'?<StatusBadge status={value}/>:value}</dd></div>)}</dl><div className="mt-6 space-y-3 border-t border-slate-100 pt-4"><Link to={`/product/${id}/edit`} className="admin-button-primary w-full"><Pencil size={16}/>Edit Product</Link><button onClick={()=>setDeleting(true)} className="admin-button-secondary w-full !text-blue-600"><Trash2 size={16}/>Delete Product</button></div></aside>
    </div>
    <section className="product-panel"><h2 className="product-panel-title">Frequently asked questions</h2>{product.faqs?.length?product.faqs.map((faq,index)=><details key={index} className="py-2 text-sm"><summary className="cursor-pointer font-medium">{faq.question}</summary><p className="py-2 text-slate-500">{faq.answer}</p></details>):<p className="text-sm text-slate-400">No questions added yet.</p>}</section><div><div className="flex gap-3 border-b border-slate-200">{['Description','Specifications','Reviews'].map((label)=><button key={label} aria-pressed={tab===label} onClick={()=>setTab(label)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab===label?'border-blue-600 text-blue-600':'border-transparent text-slate-400'}`}>{label}</button>)}</div><section className="product-panel min-h-28 !rounded-t-none text-sm leading-7 text-slate-500">{tab==='Description'?<p className="whitespace-pre-wrap">{product.description||'No description added yet.'}</p>:tab==='Reviews'?<div className="space-y-4">{product.reviews?.length?product.reviews.map((review,index)=><article key={review._id||index}><strong>{review.name} · {review.rating}/5</strong><p>{review.text}</p></article>):<p>No customer reviews available.</p>}</div>:<dl className="grid gap-3 sm:grid-cols-2">{Object.entries({Collection:product.category,Shape:product.shape,Size:product.size,Color:product.color,Gender:product.gender,...specs}).map(([key,value])=><div key={key}><dt className="inline font-semibold">{key}: </dt><dd className="inline">{value}</dd></div>)}</dl>}</section></div>
  </>}{deleting&&<ProductDialog action={{type:'delete',product}} onClose={()=>setDeleting(false)} onError={(message)=>setNotification({type:'error',message})} onSuccess={(message)=>{setDeleting(false);setNotification({type:'success',message});}}/>}{notification&&<NotificationPopup notification={notification} onClose={()=>{if(notification.type==='success')navigate('/product');else setNotification(null);}}/>}</main></DashboardLayout>;
}
