import Pagination from '../components/Pagination';
import useTablePagination from '../hooks/useTablePagination';
import VariantDeleteButton from '../components/VariantDeleteButton';
import { creationDate } from '../date';
import ActionLink from '../components/ActionLink';
import StatusBadge from '../components/StatusBadge';
import Loader from '../components/Loader';
import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Pencil, Trash2, Star, ListChecks } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import ProductDialog from '../components/ProductDialog';
import NotificationPopup from '../components/NotificationPopup';
import PopupMessage from '../components/PopupMessage';
import useProduct from '../hooks/useProduct';
import { productImageUrl } from '../api';
const money=(value)=>`₹${Number(value).toLocaleString('en-IN')}`;
export default function ProductDetails(){
  const {id}=useParams();const {loading,product,error,retry}=useProduct(id);
  const [selected,setSelected]=useState(0);const [tab,setTab]=useState('Description');
  const [deleting,setDeleting]=useState(false);const [notification,setNotification]=useState(null);const navigate=useNavigate();
  const paging=useTablePagination(product?.variants||[],5,id);
  const images=product?.images||[];
  const specs=product?{Brand:product.brand,Category:product.productType,SKU:product.sku,Stock:product.stock,Status:product.status,Subtitle:product.subtitle,'Lens types':(product.lensTypes||[]).join(', '),...(!product.hasVariants?{'Frame color':product.color,'Frame size':product.size}:{}),'Offer title':product.offerTitle,Offer:product.offerText,Delivery:product.deliveryInformation,Assurances:(product.assurances||[]).join('; '),Material:product.material,Hinge:product.hinge,Temple:product.temple,Nosepad:product.nosepad}:{};
  const summarySpecs=Object.entries(specs).filter(([key])=>['Brand','Category','SKU','Stock','Status'].includes(key));
  const visibleSpecs=Object.entries({Collection:product?.category,Shape:product?.shape,Size:product?.size,Color:product?.color,Gender:product?.gender,...specs}).filter(([,value])=>value!==null&&value!==undefined&&String(value).trim()!=='');
  return <DashboardLayout><main className="admin-page">{loading?<Loader label="Loading product"/>:error?<div><PopupMessage message={error}/><button onClick={retry} className="admin-button-secondary">Try again</button><Link to="/product" className="admin-button-secondary">Back to products</Link></div>:<>
    <div className="product-details-grid">
      <section className="product-details-gallery"><div className="product-thumb-strip">{images.map((image,index)=><button key={`${image}-${index}`} aria-label={`Show image ${index+1}`} aria-pressed={selected===index} onClick={()=>setSelected(index)}><img src={productImageUrl(image)} alt=""/></button>)}</div><img src={productImageUrl(images[selected]||product.image)} alt={product.name} className="product-large-image"/></section>
      <section className="space-y-5"><h1 className="text-xl font-bold text-slate-800">{product.name}</h1>{product.rating>0&&<p className="flex items-center gap-2 text-sm font-semibold">{product.rating}<Star size={16} className="text-amber-400" fill="currentColor"/></p>}<div className="flex flex-wrap items-center gap-3"><strong className="text-2xl">{money(product.price)}</strong>{product.originalPrice>product.price&&<><del className="text-sm text-slate-400">{money(product.originalPrice)}</del><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-600">{Math.round((1-product.price/product.originalPrice)*100)}% OFF</span></>}</div><p className={`flex items-center gap-2 text-sm font-semibold ${product.stock>0?'text-emerald-500':'text-red-500'}`}><span className="h-2 w-2 rounded-full bg-current"/>{product.stock>0?'In Stock':'Out of Stock'}</p><div><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold"><ListChecks size={16}/>Key Features</h2>{product.features?.length?<ul className="list-disc space-y-2 pl-5 text-sm text-slate-500">{product.features.map((feature,index)=><li key={index}>{feature}</li>)}</ul>:<p className="text-sm text-slate-400">No features added yet.</p>}</div></section>
      <aside className="product-panel"><dl className="space-y-5">{summarySpecs.map(([key,value])=><div key={key} className="grid grid-cols-2 gap-4 text-sm"><dt className="text-slate-400">{key}</dt><dd className="min-w-0 break-words font-medium text-slate-600">{key==='Status'?<StatusBadge status={value}/>:value}</dd></div>)}</dl><div className="mt-6 space-y-3 border-t border-slate-100 pt-4"><Link to={`/product/${id}/variants`} className="admin-button-secondary w-full">Manage variants</Link><Link to={`/product/${id}/edit`} className="admin-button-primary w-full"><Pencil size={16}/>Edit Product</Link><button onClick={()=>setDeleting(true)} className="delete-button w-full"><Trash2 size={18} aria-hidden="true" />Delete Product</button></div></aside>
    </div>
    <section className="product-panel" aria-label="Added product variants"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-bold text-slate-700">Product variants ({product.variants?.length||0})</h2><Link to={`/product/${id}/variants`} className="admin-button-secondary">Manage variants</Link></div>
      {product.variants?.length?<><div className="variant-table overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Sr. No.','Images','Size','Color','Price','Compare Price','Stock','Status','Created On','Actions'].map(label=><th key={label} scope="col" className="p-2 text-slate-500">{label}</th>)}</tr></thead><tbody>{paging.rows.map((variant,index)=><tr key={variant.id} className="border-t border-slate-100"><td className="p-2 font-medium text-slate-700">{paging.offset+index+1}</td><td className="p-2"><div className="flex gap-1">{(variant.images.length?variant.images:[product.image]).map((path,index)=><a key={`${path}-${index}`} href={productImageUrl(path)} target="_blank" rel="noreferrer" title={`View ${variant.color} ${variant.size} image ${index+1}`}><img src={productImageUrl(path)} alt={`${variant.color} ${variant.size} image ${index+1}`} className="h-10 w-10 rounded border border-slate-100 object-contain"/></a>)}</div>{!variant.images.length&&<span className="text-xs text-slate-400">Product image</span>}</td><td className="p-2">{variant.size}</td><td className="p-2">{variant.color}</td><td className="whitespace-nowrap p-2">{money(variant.price??product.price)}{variant.price===null&&<span className="block text-xs text-slate-400">Product price</span>}</td><td className="whitespace-nowrap p-2">{money(Math.max(variant.originalPrice??product.originalPrice??product.price,variant.price??product.price))}{variant.originalPrice==null&&<span className="block text-xs text-slate-400">Product compare price</span>}</td><td className="p-2">{variant.stock}</td><td className="p-2"><StatusBadge status={variant.status}/></td><td className="whitespace-nowrap p-2">{creationDate(variant.createdAt)}</td><td className="p-2"><div className="flex gap-2"><ActionLink to={`/product/${id}/variants/${variant.id}`} action="view" label="View variant"/><ActionLink to={`/product/${id}/variants/${variant.id}/edit`} action="edit" label="Edit variant"/><VariantDeleteButton productId={id} variant={variant} onDeleted={retry}/></div></td></tr>)}</tbody></table></div><Pagination page={paging.page} pageSize={paging.pageSize} total={paging.total} onPageChange={paging.setPage} label="product variants"/></>:<p className="text-sm text-slate-400">No variants added yet. Use Manage variants to add sizes, colors and images.</p>}
    </section>
    <section className="product-panel"><h2 className="product-panel-title">Frequently asked questions</h2>{product.faqs?.length?product.faqs.map((faq,index)=><details key={index} className="py-2 text-sm"><summary className="cursor-pointer font-medium">{faq.question}</summary><p className="py-2 text-slate-500">{faq.answer}</p></details>):<p className="text-sm text-slate-400">No questions added yet.</p>}</section><div><div className="flex gap-3 border-b border-slate-200">{['Description','Specifications','Reviews'].map((label)=><button key={label} aria-pressed={tab===label} onClick={()=>setTab(label)} className={`border-b-2 px-4 py-3 text-sm font-semibold ${tab===label?'border-blue-600 text-blue-600':'border-transparent text-slate-400'}`}>{label}</button>)}</div><section className="product-panel min-h-28 !rounded-t-none text-sm leading-7 text-slate-500">{tab==='Description'?<p className="whitespace-pre-wrap">{product.description||'No description added yet.'}</p>:tab==='Reviews'?<div className="space-y-4">{product.reviews?.length?product.reviews.map((review,index)=><article key={review._id||index}><strong>{review.name} · {review.rating}/5</strong><p>{review.text}</p></article>):<p>No customer reviews available.</p>}</div>:<dl className="grid gap-3 sm:grid-cols-2">{visibleSpecs.map(([key,value])=><div key={key}><dt className="inline font-semibold">{key}: </dt><dd className="inline">{value}</dd></div>)}</dl>}</section></div>
  </>}{deleting&&<ProductDialog action={{type:'delete',product}} onClose={()=>setDeleting(false)} onError={(message)=>setNotification({type:'error',message})} onSuccess={(message)=>{setDeleting(false);setNotification({type:'success',message});}}/>}{notification&&<NotificationPopup notification={notification} onClose={()=>{if(notification.type==='success')navigate('/product');else setNotification(null);}}/>}</main></DashboardLayout>;
}
